export enum ConfigConstants {
  JWT_DEFAULT_EXPIREtIME = '1h',
  JWT_ORDERING_EXPIRETIME = '8h',
  EXTERNAL_PDF_DEFAULT_EXPIRETIME = '1h',
  PASSWORD_REQUIRED_SIZE = 8,
  PAYMENT_ORDER = "720h",
  ONBOARDING_STRIPE_TOKEN = "24h",
  PHONE_VALIDATION_EXPIRETIME = '15m',
  CUSTOMER_SESSION_EXPIRETIME = '30d'
}
